import os
import pandas as pd

def process_club_handicaps():
    # 1. Load the manual data generated by your Streamlit app
    if not os.path.exists('manual_entries.csv'):
        print("No manual entries found.")
        return

    df = pd.read_csv('manual_entries.csv')
    
    # 2. Basic cleaning
    df = df.sort_values('Segment Time (s)').drop_duplicates('Name').reset_index(drop=True)
    
    # 3. Calculate dynamic handicap using the COMMUNITY ESTIMATE
    # We take the mean of all user-provided delta estimates
    group_delta = df['Delta_Estimate'].mean()
    count = len(df)
    
    # Fastest gets the full penalty, slowest gets 0 penalty
    handicaps = []
    for i in range(count):
        if count > 1:
            h = group_delta * (1 - (i / (count - 1)))
        else:
            h = 0.0
        handicaps.append(round(h))
        
    df['Handicap_Sec'] = handicaps
    df['Adjusted_Sec'] = df['Segment Time (s)'] + df['Handicap_Sec']
    
    # 4. Sort final results by Adjusted Time
    df = df.sort_values('Adjusted_Sec').reset_index(drop=True)
    df['Place'] = df.index + 1
    
    # 5. Export for Flourish
    df.to_csv("bulimba_roadies_latest.csv", index=False)
    print(f"Successfully processed {count} riders with a group-estimated delta of {round(group_delta)}s.")

if __name__ == "__main__":
    process_club_handicaps()
